# Site settings
title:          goop.nu
description:    "Personal webpage"
url:            "https://joelgoop.github.io"

# Author
author:
  name:         Joel Goop
  email:        joel@goop.nu

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
